#
#
# 
- hosts: all
  gather_facts: false
  tasks:
  - name: update DNS
    nsupdate:
        key_name: "{{ nsup_name }}"
        key_algorithm: "{{ nsup_algo }}"
        key_secret: "{{ nsup_secret }}"
        server: "192.168.33.1"
        port: 5301
        protocol: tcp
#        zone: "example.net"
#        record: "awx.example.net."
        zone: "mens.de"
        record: "awx3.mens.de."
        ttl: 60
        type: "TXT"
        value: "hola from AWX"
        state: present

